import { useState } from "react";
import { useListSignals } from "@workspace/api-client-react";
import { 
  formatCurrency, 
  formatShortDate, 
  formatNumber 
} from "@/lib/utils";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from "@/components/ui/table";
import { Activity, AlertCircle } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";

export default function SignalsPage() {
  const { data: signals, isLoading, isError } = useListSignals({ limit: 100 });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Signal History</h1>
          <p className="text-muted-foreground mt-1 text-sm">Log of all algorithmic trading signals generated by the BharatX engine.</p>
        </div>
      </div>

      {isError && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error</AlertTitle>
          <AlertDescription>Failed to load signals. Please check connection.</AlertDescription>
        </Alert>
      )}

      <Card className="bg-card/50 border-border/50 border-t-4 border-t-primary/50">
        <CardHeader className="py-4 border-b border-border/50">
          <CardTitle className="text-lg font-medium flex items-center gap-2">
            <Activity className="w-4 h-4 text-primary" />
            Signal Log
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader className="bg-muted/30">
              <TableRow className="hover:bg-transparent">
                <TableHead className="w-[180px]">Timestamp</TableHead>
                <TableHead>Symbol</TableHead>
                <TableHead>Direction</TableHead>
                <TableHead className="text-right">Price</TableHead>
                <TableHead className="text-right">Score</TableHead>
                <TableHead className="text-right">ATR</TableHead>
                <TableHead className="hidden md:table-cell">Engines</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                Array.from({ length: 10 }).map((_, i) => (
                  <TableRow key={i}>
                    <TableCell><Skeleton className="h-4 w-24" /></TableCell>
                    <TableCell><Skeleton className="h-4 w-16" /></TableCell>
                    <TableCell><Skeleton className="h-6 w-20 rounded-full" /></TableCell>
                    <TableCell className="text-right"><Skeleton className="h-4 w-20 ml-auto" /></TableCell>
                    <TableCell className="text-right"><Skeleton className="h-4 w-8 ml-auto" /></TableCell>
                    <TableCell className="text-right"><Skeleton className="h-4 w-12 ml-auto" /></TableCell>
                    <TableCell className="hidden md:table-cell"><Skeleton className="h-4 w-32" /></TableCell>
                  </TableRow>
                ))
              ) : !signals || signals.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={7} className="h-48 text-center text-muted-foreground">
                    <div className="flex flex-col items-center justify-center">
                      <Activity className="w-8 h-8 text-muted mb-2" />
                      <p>No signals recorded yet.</p>
                    </div>
                  </TableCell>
                </TableRow>
              ) : (
                signals.map((signal) => (
                  <TableRow key={signal.id} className="group data-[state=selected]:bg-muted">
                    <TableCell className="font-mono text-xs text-muted-foreground whitespace-nowrap">
                      {formatShortDate(signal.timestamp)}
                    </TableCell>
                    <TableCell className="font-bold tracking-tight">
                      {signal.symbol}
                    </TableCell>
                    <TableCell>
                      <Badge 
                        variant="outline" 
                        className={`font-bold ${
                          signal.direction === 'LONG' ? 'bg-success/10 text-success border-success/20' : 
                          signal.direction === 'SHORT' ? 'bg-destructive/10 text-destructive border-destructive/20' : 
                          'bg-warning/10 text-warning border-warning/20'
                        }`}
                        data-testid={`signal-badge-${signal.id}`}
                      >
                        {signal.direction}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right font-mono text-sm">
                      {formatCurrency(signal.price)}
                    </TableCell>
                    <TableCell className="text-right font-mono">
                      {signal.totalScore}
                    </TableCell>
                    <TableCell className="text-right font-mono text-xs text-muted-foreground">
                      {formatNumber(signal.atr, 2)}
                    </TableCell>
                    <TableCell className="hidden md:table-cell">
                      <div className="flex gap-1 flex-wrap max-w-[200px]">
                        {signal.engines?.map(e => (
                          <div 
                            key={e.name} 
                            className={`w-2 h-2 rounded-full ${
                              e.status === 'BULL' ? 'bg-success' : 
                              e.status === 'BEAR' ? 'bg-destructive' : 
                              'bg-muted-foreground'
                            }`}
                            title={`${e.name}: ${e.status} (${e.score})`}
                          />
                        ))}
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  );
}
